using AppAlbumFigurinhas.Models;

namespace AppAlbumFigurinhas.Services
{
    public static class JogadoresDataService
    {
        // Retorna a lista completa de todos os jogadores do álbum
        public static List<(string Nome, string Selecao, string Tipo)> GetTodosJogadores()
        {
            return new List<(string, string, string)>
    {
            // Algeria
                ("Aissa Mandi", "Algeria", "Comum"),
                ("Alexis Guendouz", "Algeria", "Comum"),
                ("Amine Gouiri", "Algeria", "Comum"),
                ("Anis Hadj Moussa", "Algeria", "Comum"),
                ("Baghdad Bounedjah", "Algeria", "Comum"),
                ("Fares Chaibi", "Algeria", "Comum"),
                ("Hicham Boudaoui", "Algeria", "Comum"),
                ("Houssem Aquar", "Algeria", "Comum"),
                ("Ismael Bennacer", "Algeria", "Comum"),
                ("Mohamed Amine Tougai", "Algeria", "Comum"),
                ("Mohammed Amoura", "Algeria", "Comum"),
                ("Ramiz Zerrouki", "Algeria", "Comum"),
                ("Ramy Bensebaini", "Algeria", "Comum"),
                ("Rayan Ait-Nouri", "Algeria", "Comum"),
                ("Riyad Mahrez", "Algeria", "Comum"),
                ("Riyad Mahrez", "Algeria", "Comum"),
                ("Said Benrahma", "Algeria", "Comum"),
                ("Team Logo", "Algeria", "Comum"),
                ("Youcef Atal", "Algeria", "Comum"),
                // Argentina
                ("Alexis Mac Allister", "Argentina", "Comum"),
                ("Cristian Romero", "Argentina", "Comum"),
                ("Emiliano Martinez", "Argentina", "Comum"),
                ("Emiliano Martinez", "Argentina", "Especial"),
                ("Emiliano Martinez", "Argentina", "Especial"),
                ("Enzo Fernandez", "Argentina", "Comum"),
                ("Exequiel Palacios", "Argentina", "Comum"),
                ("Franco Mastantuono", "Argentina", "Comum"),
                ("Giuliano Simeone", "Argentina", "Comum"),
                ("Julian Alvarez", "Argentina", "Comum"),
                ("Lautaro Martinez", "Argentina", "Comum"),
                ("Lautaro Martinez", "Argentina", "Especial"),
                ("Leandro Paredes", "Argentina", "Comum"),
                ("Leonardo Balerdi", "Argentina", "Comum"),
                ("Lionel Messi", "Argentina", "Comum"),
                ("Lionel Messi", "Argentina", "Especial"),
                ("Lionel Messi", "Argentina", "Especial"),
                ("Nahuel Molina", "Argentina", "Comum"),
                ("Nico Gonzalez", "Argentina", "Comum"),
                ("Nico Paz", "Argentina", "Comum"),
                ("Nicolas Otamendi", "Argentina", "Comum"),
                ("Nicolas Tagliafico", "Argentina", "Comum"),
                ("Rodrigo De Paul", "Argentina", "Comum"),
                ("Team Logo", "Argentina", "Comum"),
                ("Team Photo", "Argentina", "Comum"),
                ("Team Photo", "Argentina", "Comum"),
                // Australia
                ("Aiden O'Neill", "Australia", "Comum"),
                ("Alessandro Circati", "Australia", "Comum"),
                ("Aziz Behich", "Australia", "Comum"),
                ("Cameron Burgess", "Australia", "Comum"),
                ("Craig Goodwin", "Australia", "Comum"),
                ("Harry Souttar", "Australia", "Comum"),
                ("Jackson Irvine", "Australia", "Comum"),
                ("Jordan Bos", "Australia", "Comum"),
                ("Jordan Bos", "Australia", "Comum"),
                ("Kusini Vengi", "Australia", "Comum"),
                ("Lewis Miller", "Australia", "Comum"),
                ("Mathew Ryan", "Australia", "Comum"),
                ("Mathew Ryan", "Australia", "Especial"),
                ("Milos Degenek", "Australia", "Comum"),
                ("Nestory Irankunda", "Australia", "Comum"),
                // Austria
                ("Alexander Prass", "Austria", "Comum"),
                ("Alexander Schlager", "Austria", "Comum"),
                ("Christoph Baumgartner", "Austria", "Comum"),
                ("Christoph Baumgartner", "Austria", "Comum"),
                ("David Alaba", "Austria", "Comum"),
                ("Kevin Danso", "Austria", "Comum"),
                ("Konrad Laimer", "Austria", "Comum"),
                ("Marcel Sabitzer", "Austria", "Comum"),
                ("Michael Gregoritsch", "Austria", "Comum"),
                ("Nicolas Seiwald", "Austria", "Comum"),
                ("Patrick Pentz", "Austria", "Comum"),
                ("Patrick Wimmer", "Austria", "Comum"),
                ("Philipp Lienhart", "Austria", "Comum"),
                ("Phillipp Mwene", "Austria", "Comum"),
                ("Romano Schmid", "Austria", "Comum"),
                ("Stefan Posch", "Austria", "Comum"),
                ("Team Logo", "Austria", "Comum"),
                ("Xaver Schlager", "Austria", "Comum"),
                // Belgium
                ("Alexis Saelemaekers", "Belgium", "Comum"),
                ("Amadou Onana", "Belgium", "Comum"),
                ("Arthur Theate", "Belgium", "Comum"),
                ("Brandon Mechele", "Belgium", "Comum"),
                ("Hans Vanaken", "Belgium", "Comum"),
                ("Jeremy Doku", "Belgium", "Comum"),
                ("Kevin De Bruyne", "Belgium", "Comum"),
                ("Lois Openda", "Belgium", "Comum"),
                ("Maxim De Cuyper", "Belgium", "Comum"),
                ("Nicolas Raskin", "Belgium", "Comum"),
                ("Romelu Lukaku", "Belgium", "Comum"),
                ("Team Logo", "Belgium", "Comum"),
                ("Thibaut Courtois", "Belgium", "Especial"),
                ("Thomas Meunier", "Belgium", "Comum"),
                ("Timothy Castagne", "Belgium", "Comum"),
                ("Youri Tielemans", "Belgium", "Comum"),
                ("Zeno Debast", "Belgium", "Comum"),
                // Bosnia and Herzegovina
                ("Amar Memic", "Bosnia and Herzegovina", "Comum"),
                ("Amir Hadziahmetovic", "Bosnia and Herzegovina", "Comum"),
                ("Benjamin Tahirovic", "Bosnia and Herzegovina", "Comum"),
                ("Edin Dzeko", "Bosnia and Herzegovina", "Comum"),
                ("Haris Tabakovic", "Bosnia and Herzegovina", "Comum"),
                ("Ivan Basic", "Bosnia and Herzegovina", "Comum"),
                ("Ivan Sunjic", "Bosnia and Herzegovina", "Comum"),
                ("Nihad Mujakic", "Bosnia and Herzegovina", "Comum"),
                ("Nikola Vasilj", "Bosnia and Herzegovina", "Comum"),
                ("Samed Bazdar", "Bosnia and Herzegovina", "Comum"),
                ("Sead Kolasinac", "Bosnia and Herzegovina", "Comum"),
                ("Tarik Muharemovic", "Bosnia and Herzegovina", "Comum"),
                ("Team Logo", "Bosnia and Herzegovina", "Comum"),
                // Brasil (coleção própria)
                ("Brasil", "Brasil", "Comum"),
                ("Brasil", "Brasil", "Comum"),
                ("Neymar Jr", "Brasil", "Comum"),
                ("Neymar Jr", "Brasil", "Comum"),
                ("Neymar Jr", "Brasil", "Comum"),
                ("Neymar Jr", "Brasil", "Comum"),
                ("Neymar Jr", "Brasil", "Especial"),
                ("Neymar Jr", "Brasil", "Especial"),
                ("Neymar Jr", "Brasil", "Especial"),
                ("Neymar Jr", "Brasil", "Especial"),
                ("Neymar Jr", "Brasil", "Especial"),
                ("Neymar Jr", "Brasil", "Especial"),
                ("Neymar Jr", "Brasil", "Especial"),
                ("Neymar Jr", "Brasil", "Especial"),
                ("Neymar Jr", "Brasil", "Especial"),
                ("Neymar Jr", "Brasil", "Especial"),
                ("Neymar Jr", "Brasil", "Especial"),
                ("Neymar Jr", "Brasil", "Especial"),
                ("Neymar Jr", "Brasil", "Especial"),
                ("Neymar Jr", "Brasil", "Especial"),
                ("Neymar Jr", "Brasil", "Especial"),
                ("Neymar Jr", "Brasil", "Especial"),
                ("Neymar Jr", "Brasil", "Especial"),
                ("Neymar Jr", "Brasil", "Especial"),
                ("Neymar Jr", "Brasil", "Especial"),
                ("Neymar Jr", "Brasil", "Especial"),
                ("Neymar Jr", "Brasil", "Especial"),
                ("Neymar Jr", "Brasil", "Especial"),
                ("Neymar Jr", "Brasil", "Especial"),
                ("Neymar Jr", "Brasil", "Especial"),
                ("Neymar Jr", "Brasil", "Especial"),
                // Brazil
                ("Alisson", "Brazil", "Comum"),
                ("Bento", "Brazil", "Comum"),
                ("Bento", "Brazil", "Comum"),
                ("Bruno Guimaraes", "Brazil", "Comum"),
                ("Casemiro", "Brazil", "Comum"),
                ("Danilo", "Brazil", "Comum"),
                ("Eder Militao", "Brazil", "Comum"),
                ("Estevao", "Brazil", "Comum"),
                ("Gabriel Magalhaes", "Brazil", "Comum"),
                ("Gabriel Magalhaes", "Brazil", "Especial"),
                ("Gabriel Magalhaes", "Brazil", "Especial"),
                ("Gabriel Martinelli", "Brazil", "Comum"),
                ("Joao Pedro", "Brazil", "Comum"),
                ("Lucas Paqueta", "Brazil", "Comum"),
                ("Luiz Henrique", "Brazil", "Comum"),
                ("Marquinhos", "Brazil", "Comum"),
                ("Matheus Cunha", "Brazil", "Comum"),
                ("Neymar Jr", "Brazil", "Especial"),
                ("Raphinha", "Brazil", "Comum"),
                ("Rodrygo", "Brazil", "Comum"),
                ("Team Logo", "Brazil", "Comum"),
                ("Team Photo", "Brazil", "Comum"),
                ("Team Photo", "Brazil", "Comum"),
                ("Vinicius Junior", "Brazil", "Comum"),
                ("Wesley", "Brazil", "Comum"),
                // Canada
                ("Alphonso Davies", "Canada", "Comum"),
                ("Alphonso Davies", "Canada", "Especial"),
                ("Alphonso Davies", "Canada", "Especial"),
                ("Cyle Larin", "Canada", "Comum"),
                ("Dayne St.Clair", "Canada", "Comum"),
                ("Derek Cornelius", "Canada", "Comum"),
                ("Ismael Kone", "Canada", "Comum"),
                ("Jonathan David", "Canada", "Comum"),
                ("Jonathan Osorio", "Canada", "Comum"),
                ("Kamal Miller", "Canada", "Comum"),
                ("Liam Millar", "Canada", "Comum"),
                ("Mathieu Choiniere", "Canada", "Comum"),
                ("Moise Bombito", "Canada", "Comum"),
                ("Niko Sigur", "Canada", "Comum"),
                ("Riche Larvea", "Canada", "Comum"),
                ("Samuel Adekugbe", "Canada", "Comum"),
                ("Stephen Eustaquio", "Canada", "Comum"),
                ("Tajon Buchanan", "Canada", "Comum"),
                ("Team Logo", "Canada", "Comum"),
                // Cape Verde
                ("Bebe", "Cape Verde", "Comum"),
                ("Dailon Livramento", "Cape Verde", "Comum"),
                ("Dailon Livramento", "Cape Verde", "Comum"),
                ("Deroy Duarte", "Cape Verde", "Comum"),
                ("Diney", "Cape Verde", "Comum"),
                ("Joao Paulo", "Cape Verde", "Comum"),
                ("Jovane Cabral", "Cape Verde", "Comum"),
                ("Kevin Pina", "Cape Verde", "Comum"),
                ("Logan Costa", "Cape Verde", "Comum"),
                ("Patrick Andrade", "Cape Verde", "Comum"),
                ("Pico", "Cape Verde", "Comum"),
                ("Ryan Mendes", "Cape Verde", "Comum"),
                ("Steven Moreira", "Cape Verde", "Comum"),
                ("Vozinha", "Cape Verde", "Comum"),
                ("Wagner Pina", "Cape Verde", "Comum"),
                ("Willy Semedo", "Cape Verde", "Comum"),
                ("Yannick Semedo", "Cape Verde", "Comum"),
                // Colombia
                ("Camilo Vargas", "Colombia", "Comum"),
                ("Daniel Munoz", "Colombia", "Comum"),
                ("David Ospina", "Colombia", "Comum"),
                ("Davinson Sanchez", "Colombia", "Comum"),
                ("James Rodriguez", "Colombia", "Comum"),
                ("Jefferson Lerma", "Colombia", "Comum"),
                ("Jefferson Lerma", "Colombia", "Especial"),
                ("Jefferson Lerma", "Colombia", "Especial"),
                ("Jhon Cordova", "Colombia", "Comum"),
                ("Jhon Lucumi", "Colombia", "Comum"),
                ("Johan Mojica", "Colombia", "Comum"),
                ("Jon Arias", "Colombia", "Comum"),
                ("Jorge Carrascal", "Colombia", "Comum"),
                ("Juan Fernando Quintero", "Colombia", "Comum"),
                ("Kevin Castano", "Colombia", "Comum"),
                ("Luis Diaz", "Colombia", "Comum"),
                ("Luis Diaz", "Colombia", "Comum"),
                ("Luis Suarez", "Colombia", "Comum"),
                ("Richard Rios", "Colombia", "Comum"),
                ("Santiago Arias", "Colombia", "Comum"),
                ("Team Logo", "Colombia", "Comum"),
                ("Team Photo", "Colombia", "Comum"),
                ("Team Photo", "Colombia", "Comum"),
                ("Yerry Mina", "Colombia", "Comum"),
                // Cote d'Ivoire
                ("Amad Diallo", "Cote d'Ivoire", "Comum"),
                ("Emmanuel Agbadou", "Cote d'Ivoire", "Comum"),
                ("Evan Ndicka", "Cote d'Ivoire", "Comum"),
                ("Evan Ndicka", "Cote d'Ivoire", "Comum"),
                ("Evann Guessand", "Cote d'Ivoire", "Comum"),
                ("Ghislain Konan", "Cote d'Ivoire", "Comum"),
                ("Ibrahim Sangare", "Cote d'Ivoire", "Comum"),
                ("Jean-Philippe Gbamin", "Cote d'Ivoire", "Comum"),
                ("Odilon Kossounou", "Cote d'Ivoire", "Comum"),
                ("Oumar Diakite", "Cote d'Ivoire", "Comum"),
                ("Ousmane Diomande", "Cote d'Ivoire", "Comum"),
                ("Sebastien Haller", "Cote d'Ivoire", "Comum"),
                ("Seko Fofana", "Cote d'Ivoire", "Comum"),
                ("Simon Adingra", "Cote d'Ivoire", "Comum"),
                ("Team Logo", "Cote d'Ivoire", "Comum"),
                ("Wilfried Singo", "Cote d'Ivoire", "Comum"),
                ("Willy Boly", "Cote d'Ivoire", "Comum"),
                ("Yahia Fofana", "Cote d'Ivoire", "Comum"),
                ("Yan Diomande", "Cote d'Ivoire", "Comum"),
                ("Yan Diomande", "Cote d'Ivoire", "Comum"),
                // Croatia
                ("Andrej Kramaric", "Croatia", "Comum"),
                ("Ante Budimir", "Croatia", "Comum"),
                ("Duje Caleta-Car", "Croatia", "Comum"),
                ("Franjo Ivanovic", "Croatia", "Comum"),
                ("Ivan Perisic", "Croatia", "Comum"),
                ("Josko Gvardiol", "Croatia", "Comum"),
                ("Josko Gvardiol", "Croatia", "Especial"),
                ("Josko Gvardiol", "Croatia", "Especial"),
                ("Kristijan Jakic", "Croatia", "Comum"),
                ("Lovro Majer", "Croatia", "Comum"),
                ("Luka Modric", "Croatia", "Comum"),
                ("Luka Modric", "Croatia", "Especial"),
                ("Luka Modric", "Croatia", "Especial"),
                ("Luka Vuskovic", "Croatia", "Comum"),
                ("Mario Pasalic", "Croatia", "Comum"),
                ("Martin Baturina", "Croatia", "Comum"),
                // Curacao
                ("Armando Obispo", "Curacao", "Comum"),
                ("Eloy Room", "Curacao", "Comum"),
                ("Gervane Kastaneer", "Curacao", "Comum"),
                ("Godfried Roemeratoe", "Curacao", "Comum"),
                ("Jearl Margaritha", "Curacao", "Comum"),
                ("Jeremy Antonisse", "Curacao", "Comum"),
                ("Joshua Brenet", "Curacao", "Comum"),
                ("Juninho Bacuna", "Curacao", "Comum"),
                ("Jurgen Locadia", "Curacao", "Comum"),
                ("Jurien Gaari", "Curacao", "Comum"),
                ("Kenji Gorre", "Curacao", "Comum"),
                ("Leandro Bacuna", "Curacao", "Especial"),
                ("Roshon Van Eijma", "Curacao", "Comum"),
                ("Sherel Floranus", "Curacao", "Comum"),
                ("Shurandy Sambo", "Curacao", "Comum"),
                ("Sontje Hansen", "Curacao", "Comum"),
                // Czechia
                ("Adam Hlozek", "Czechia", "Comum"),
                ("David Zima", "Czechia", "Comum"),
                ("Jaroslav Zeleny", "Czechia", "Comum"),
                ("Jindrich Stanek", "Czechia", "Comum"),
                ("Ladislav Krejci", "Czechia", "Comum"),
                ("Lukas Cerv", "Czechia", "Comum"),
                ("Lukas Provod", "Czechia", "Comum"),
                ("Matej Kovar", "Czechia", "Comum"),
                ("Matej Vydra", "Czechia", "Comum"),
                ("Michal Sadilek", "Czechia", "Comum"),
                ("Patrik Schick", "Czechia", "Comum"),
                ("Pavel Sulc", "Czechia", "Comum"),
                ("Team Logo", "Czechia", "Comum"),
                ("Tomas Chory", "Czechia", "Comum"),
                ("Tomas Holes", "Czechia", "Comum"),
                ("Vaclav Cerny", "Czechia", "Comum"),
                ("Vaclav Cerny", "Czechia", "Comum"),
                ("Vasil Kusej", "Czechia", "Comum"),
                // DR Congo
                ("Aaron Wan-Bissaka", "DR Congo", "Comum"),
                ("Arthur Masuaku", "DR Congo", "Comum"),
                ("Axel Tuanzebe", "DR Congo", "Comum"),
                ("Brian Cipenga", "DR Congo", "Comum"),
                ("Cedric Bakambu", "DR Congo", "Comum"),
                ("Chancel Mbemba", "DR Congo", "Comum"),
                ("Charles Pickel", "DR Congo", "Comum"),
                ("Edo Kayembe", "DR Congo", "Comum"),
                ("Fiston Mayele", "DR Congo", "Comum"),
                ("Joris Kayembe", "DR Congo", "Comum"),
                ("Lionel Mpasi", "DR Congo", "Comum"),
                ("Meschak Elia", "DR Congo", "Comum"),
                ("Nathanael Mbuku", "DR Congo", "Comum"),
                ("Ngal'ayel Mukau", "DR Congo", "Comum"),
                ("Samuel Moutoussamy", "DR Congo", "Comum"),
                ("Theo Bongonda", "DR Congo", "Comum"),
                ("Yoane Wissa", "DR Congo", "Comum"),
                // Ecuador
                ("Alan Franco", "Ecuador", "Comum"),
                ("Alan Minda", "Ecuador", "Comum"),
                ("Angelo Preciado", "Ecuador", "Comum"),
                ("Enner Valencia", "Ecuador", "Comum"),
                ("Enner Valencia", "Ecuador", "Especial"),
                ("Enner Valencia", "Ecuador", "Especial"),
                ("Gonzalo Plata", "Ecuador", "Comum"),
                ("Gonzalo Valle", "Ecuador", "Comum"),
                ("Hernan Galindez", "Ecuador", "Comum"),
                ("Joel Ordonez", "Ecuador", "Comum"),
                ("John Veboah", "Ecuador", "Comum"),
                ("Kendry Paez", "Ecuador", "Comum"),
                ("Kevin Rodriguez", "Ecuador", "Comum"),
                ("Leonardo Campana", "Ecuador", "Comum"),
                ("Moises Caicedo", "Ecuador", "Comum"),
                ("Moises Caicedo", "Ecuador", "Especial"),
                ("Nilson Angulo", "Ecuador", "Comum"),
                ("Pedro Vite", "Ecuador", "Comum"),
                ("Pervis Estupinan", "Ecuador", "Comum"),
                ("Piero Hincapie", "Ecuador", "Comum"),
                ("Team Logo", "Ecuador", "Comum"),
                ("Team Logo", "Ecuador", "Comum"),
                ("Team Photo", "Ecuador", "Comum"),
                ("Team Photo", "Ecuador", "Comum"),
                ("Willian Pacho", "Ecuador", "Comum"),
                // Egypt
                ("Ahmed Fatouh", "Egypt", "Comum"),
                ("Khaled Sobhi", "Egypt", "Comum"),
                ("Khaled Sobhi", "Egypt", "Comum"),
                ("Mohamed El Shenawy", "Egypt", "Comum"),
                ("Mohamed Hamdy", "Egypt", "Comum"),
                ("Mohamed Lasheen", "Egypt", "Comum"),
                ("Mohamed Salah", "Egypt", "Comum"),
                ("Mohamed Salah", "Egypt", "Especial"),
                ("Omar Marmoush", "Egypt", "Comum"),
                ("Ramy Rabia", "Egypt", "Comum"),
                ("Team Logo", "Egypt", "Comum"),
                ("Trezeguet", "Egypt", "Comum"),
                // England
                ("Anthony Gordon", "England", "Comum"),
                ("Bukayo Saka", "England", "Comum"),
                ("Cole Palmer", "England", "Comum"),
                ("Cole Palmer", "England", "Comum"),
                ("Dan Burn", "England", "Comum"),
                ("Declan Rice", "England", "Comum"),
                ("Ezri Konsa", "England", "Comum"),
                ("Harry Kane", "England", "Comum"),
                ("Harry Kane", "England", "Especial"),
                ("John Stones", "England", "Comum"),
                ("Jordan Henderson", "England", "Comum"),
                ("Jordan Pickford", "England", "Comum"),
                ("Jude Bellingham", "England", "Comum"),
                ("Jude Bellingham", "England", "Especial"),
                ("Marc Guehi", "England", "Comum"),
                ("Marcus Rashford", "England", "Comum"),
                ("Morgan Rogers", "England", "Comum"),
                ("Ollie Watkins", "England", "Comum"),
                ("Phil Foden", "England", "Comum"),
                ("Team Logo", "England", "Comum"),
                // France
                ("Adrien Rabiot", "France", "Comum"),
                ("Aurelien Tchouameni", "France", "Comum"),
                ("Bradley Barcola", "France", "Comum"),
                ("Dayot Upamecano", "France", "Comum"),
                ("Desire Doue", "France", "Comum"),
                ("Eduardo Camavinga", "France", "Comum"),
                ("Hugo Ekitike", "France", "Comum"),
                ("Ibrahima Konate", "France", "Comum"),
                ("Jules Kounde", "France", "Comum"),
                ("Kingsley Coman", "France", "Comum"),
                ("Kylian Mbappe", "France", "Comum"),
                ("Kylian Mbappe", "France", "Especial"),
                ("Lucas Digne", "France", "Comum"),
                ("Manu Kone", "France", "Comum"),
                ("Manu Kone", "France", "Comum"),
                ("Michael Olise", "France", "Comum"),
                ("Mike Maignan", "France", "Comum"),
                ("Ousmane Dembele", "France", "Comum"),
                ("Team Logo", "France", "Comum"),
                ("Team Photo", "France", "Comum"),
                ("Team Photo", "France", "Comum"),
                ("Theo Hernandez", "France", "Comum"),
                ("William Saliba", "France", "Comum"),
                // Germany
                ("Antonio Rudiger", "Germany", "Comum"),
                ("Felix Nmecha", "Germany", "Comum"),
                ("Florian Wirtz", "Germany", "Comum"),
                ("Jamal Musiala", "Germany", "Comum"),
                ("Jamal Musiala", "Germany", "Especial"),
                ("Jonathan Tah", "Germany", "Comum"),
                ("Joshua Kimmich", "Germany", "Especial"),
                ("Joshua Kimmich", "Germany", "Especial"),
                ("Kai Havertz", "Germany", "Comum"),
                ("Leon Goretzka", "Germany", "Comum"),
                ("Marc-Andre ter Stegen", "Germany", "Comum"),
                ("Maximilian Mittelstadt", "Germany", "Comum"),
                ("Nick Woltemade", "Germany", "Comum"),
                ("Nico Schlotterbeck", "Germany", "Comum"),
                ("Ridle Baku", "Germany", "Comum"),
                ("Serge Gnabry", "Germany", "Comum"),
                ("Team Logo", "Germany", "Comum"),
                // Ghana
                ("Abdul Issahaku Fatawu", "Ghana", "Comum"),
                ("Alexander Djiku", "Ghana", "Comum"),
                ("Alidu Seidu", "Ghana", "Comum"),
                ("Antoine Semenyo", "Ghana", "Comum"),
                ("Caleb Yirenkyi", "Ghana", "Comum"),
                ("Inaki Williams", "Ghana", "Comum"),
                ("Inaki Williams", "Ghana", "Comum"),
                ("Jordan Ayew", "Ghana", "Comum"),
                ("Joseph Paintsil", "Ghana", "Comum"),
                ("Kamaldeen Sulemana", "Ghana", "Comum"),
                ("Mohammed Salisu", "Ghana", "Comum"),
                ("Osman Bukari", "Ghana", "Comum"),
                ("Salis Abdul Samed", "Ghana", "Comum"),
                ("Tariq Lamptey", "Ghana", "Comum"),
                ("Team Logo", "Ghana", "Comum"),
                ("Team Photo", "Ghana", "Comum"),
                ("Thomas Partey", "Ghana", "Comum"),
                // Haiti
                ("Carlens Arcus", "Haiti", "Comum"),
                ("Christopher Attys", "Haiti", "Comum"),
                ("Danley Jean Jacques", "Haiti", "Comum"),
                ("Derrick Etienne Jr", "Haiti", "Comum"),
                ("Duckens Nazon", "Haiti", "Comum"),
                ("Duke Lacroix", "Haiti", "Comum"),
                ("Frantzdy Pierrot", "Haiti", "Comum"),
                ("Hannes Delcroix", "Haiti", "Comum"),
                ("Jean-Kevin Duverne", "Haiti", "Comum"),
                ("Jean-Ricner Bellegarde", "Haiti", "Comum"),
                ("Johny Placide", "Haiti", "Comum"),
                ("Josue Casimir", "Haiti", "Comum"),
                ("Leverton Pierre", "Haiti", "Comum"),
                ("Louicius Deedson", "Haiti", "Comum"),
                ("Martin Experience", "Haiti", "Comum"),
                ("Ricardo Ade", "Haiti", "Comum"),
                ("Team Logo", "Haiti", "Comum"),
                // Iran
                ("Alireza Beiranvand", "Iran", "Comum"),
                ("Alireza Jahanbakhsh", "Iran", "Comum"),
                ("Hossein Kanaani", "Iran", "Comum"),
                ("Mehdi Taremi", "Iran", "Comum"),
                ("Milad Mohammadi", "Iran", "Comum"),
                ("Mohammad Mohebi", "Iran", "Comum"),
                ("Morteza Pouraliganji", "Iran", "Comum"),
                ("Omid Noorafkan", "Iran", "Comum"),
                ("Roozbeh Cheshmi", "Iran", "Comum"),
                ("Saeed Ezatolahi", "Iran", "Comum"),
                ("Saleh Hardani", "Iran", "Comum"),
                ("Saman Ghoddos", "Iran", "Comum"),
                ("Sardar Azmoun", "Iran", "Comum"),
                ("Shojae Khalilzadeh", "Iran", "Comum"),
                ("Team Logo", "Iran", "Comum"),
                // Iraq
                ("Aimar Sher", "Iraq", "Comum"),
                ("Akam Hashem", "Iraq", "Comum"),
                ("Ali Al-Hamadi", "Iraq", "Comum"),
                ("Ali Jasim", "Iraq", "Comum"),
                ("Hussein Ali", "Iraq", "Comum"),
                ("Ibrahim Bavesh", "Iraq", "Comum"),
                ("Jalal Hassan", "Iraq", "Comum"),
                ("Manaf Younis", "Iraq", "Comum"),
                ("Marko Farji", "Iraq", "Comum"),
                ("Merchas Doski", "Iraq", "Comum"),
                ("Mohanad Ali", "Iraq", "Comum"),
                ("Osama Rashid", "Iraq", "Comum"),
                ("Rebin Sulaka", "Iraq", "Comum"),
                ("Team Logo", "Iraq", "Comum"),
                ("Youssef Amyn", "Iraq", "Comum"),
                ("Zaid Tahseen", "Iraq", "Comum"),
                ("Zidane Iqbal", "Iraq", "Comum"),
                // Japan
                ("Ao Tanaka", "Japan", "Comum"),
                ("Ayase Ueda", "Japan", "Comum"),
                ("Daichi Kamada", "Japan", "Comum"),
                ("Junnosuke Suzuki", "Japan", "Comum"),
                ("Junya Ito", "Japan", "Comum"),
                ("Kaishu Sano", "Japan", "Comum"),
                ("Keito Nakamura", "Japan", "Comum"),
                ("Shogo Taniguchi", "Japan", "Comum"),
                ("Shuto Machino", "Japan", "Comum"),
                ("Takefusa Kubo", "Japan", "Comum"),
                ("Takefusa Kubo", "Japan", "Comum"),
                ("Takumi Minamino", "Japan", "Comum"),
                ("Team Logo", "Japan", "Comum"),
                ("Tsuyoshi Watanabe", "Japan", "Comum"),
                ("Yuki Soma", "Japan", "Comum"),
                // Jordan
                ("Ali Olwan", "Jordan", "Comum"),
                ("Amer Jamous", "Jordan", "Comum"),
                ("Ibrahim Saadeh", "Jordan", "Comum"),
                ("Ibrahim Sabra", "Jordan", "Comum"),
                ("Ihsan Haddad", "Jordan", "Comum"),
                ("Mahmoud Al-Mardi", "Jordan", "Comum"),
                ("Mohammad Abu Hashish", "Jordan", "Comum"),
                ("Mohammad Abu Zrayq", "Jordan", "Comum"),
                ("Mohammad Abualnadi", "Jordan", "Comum"),
                ("Mohannad Abu Taha", "Jordan", "Comum"),
                ("Musa Al-Taamari", "Jordan", "Comum"),
                ("Nizar Al-Rashdan", "Jordan", "Comum"),
                ("Noor Al-Rawabdeh", "Jordan", "Comum"),
                ("Saleem Obaid", "Jordan", "Comum"),
                ("Yazan Al-Arab", "Jordan", "Comum"),
                ("Yazan Al-Naimat", "Jordan", "Comum"),
                ("Yazeed Abulaila", "Jordan", "Comum"),
                // Mexico
                ("Alexis Vega", "Mexico", "Comum"),
                ("Carlos Rodriguez", "Mexico", "Comum"),
                ("Cesar Huerta", "Mexico", "Comum"),
                ("Cesar Montes", "Mexico", "Comum"),
                ("Diego Lainez", "Mexico", "Comum"),
                ("Edson Alvarez", "Mexico", "Comum"),
                ("Erick Sanchez", "Mexico", "Comum"),
                ("Gilberto Mora", "Mexico", "Comum"),
                ("Hirving Lozano", "Mexico", "Comum"),
                ("Israel Reyes", "Mexico", "Comum"),
                ("Jesus Gallardo", "Mexico", "Comum"),
                ("Johan Vasquez", "Mexico", "Comum"),
                ("Jorge Sanchez", "Mexico", "Comum"),
                ("Luis Malagon", "Mexico", "Comum"),
                ("Marcel Ruiz", "Mexico", "Comum"),
                ("Orbelin Pineda", "Mexico", "Comum"),
                ("Raul Jimenez", "Mexico", "Comum"),
                ("Raul Jimenez", "Mexico", "Especial"),
                ("Raul Jimenez", "Mexico", "Especial"),
                ("Roberto Alvarado", "Mexico", "Comum"),
                ("Santiago Gimenez", "Mexico", "Comum"),
                ("Santiago Gimenez", "Mexico", "Comum"),
                ("Santiago Gimenez", "Mexico", "Especial"),
                ("Team Logo", "Mexico", "Comum"),
                ("Team Photo", "Mexico", "Comum"),
                ("Team Photo", "Mexico", "Comum"),
                // Morocco
                ("Abde Ezzalzouli", "Morocco", "Comum"),
                ("Adam Masina", "Morocco", "Comum"),
                ("Ayoub El Kaabi", "Morocco", "Comum"),
                ("Bilal El Khannouss", "Morocco", "Comum"),
                ("Brahim Diaz", "Morocco", "Comum"),
                ("Brahim Diaz", "Morocco", "Comum"),
                ("Eliesse Ben Seghir", "Morocco", "Comum"),
                ("Ismael Saibari", "Morocco", "Comum"),
                ("Jawad El Yamio", "Morocco", "Comum"),
                ("Nayef Aguerd", "Morocco", "Comum"),
                ("Roman Saiss", "Morocco", "Comum"),
                ("Sofyan Amrabat", "Morocco", "Comum"),
                ("Team Logo", "Morocco", "Comum"),
                ("Team Photo", "Morocco", "Comum"),
                ("Yassine Bounou", "Morocco", "Comum"),
                ("Youssef En-Nesyri", "Morocco", "Comum"),
                // Netherlands
                ("Bart Verbruggen", "Netherlands", "Comum"),
                ("Cody Gakpo", "Netherlands", "Comum"),
                ("Denzel Dumfries", "Netherlands", "Comum"),
                ("Donyell Malen", "Netherlands", "Comum"),
                ("Frenkie de Jong", "Netherlands", "Comum"),
                ("Jan Paul van Hecke", "Netherlands", "Comum"),
                ("Jeremie Frimpong", "Netherlands", "Comum"),
                ("Jurrien Timber", "Netherlands", "Comum"),
                ("Justin Kluivert", "Netherlands", "Comum"),
                ("Memphis Depay", "Netherlands", "Comum"),
                ("Micky van de Ven", "Netherlands", "Comum"),
                ("Nathan Ake", "Netherlands", "Comum"),
                ("Ryan Gravenberch", "Netherlands", "Comum"),
                ("Team Logo", "Netherlands", "Comum"),
                ("Team Photo", "Netherlands", "Comum"),
                ("Team Photo", "Netherlands", "Comum"),
                ("Teun Koopmeiners", "Netherlands", "Comum"),
                ("Tijjani Reijnders", "Netherlands", "Comum"),
                ("Virgil van Dijk", "Netherlands", "Comum"),
                ("Virgil van Dijk", "Netherlands", "Especial"),
                ("Virgil van Dijk", "Netherlands", "Especial"),
                ("Virgil van Dijk", "Netherlands", "Especial"),
                ("Wout Weghorst", "Netherlands", "Comum"),
                ("Xavi Simons", "Netherlands", "Comum"),
                // New Zealand
                ("Alex Paulsen", "New Zealand", "Comum"),
                ("Callum McCowatt", "New Zealand", "Comum"),
                ("Chris Wood", "New Zealand", "Comum"),
                ("Finn Surman", "New Zealand", "Comum"),
                ("Francis de Vries", "New Zealand", "Comum"),
                ("Joe Bell", "New Zealand", "Comum"),
                ("Joe Bell", "New Zealand", "Comum"),
                ("Kosta Barbarouses", "New Zealand", "Comum"),
                ("Liberato Cacace", "New Zealand", "Comum"),
                ("Marko Stamenic", "New Zealand", "Comum"),
                ("Matthew Garbett", "New Zealand", "Comum"),
                ("Max Crocombe Payne", "New Zealand", "Comum"),
                ("Michael Boxall", "New Zealand", "Comum"),
                ("Ryan Thomas", "New Zealand", "Comum"),
                ("Team Logo", "New Zealand", "Comum"),
                ("Tim Payne", "New Zealand", "Comum"),
                // Norway
                ("Andreas Schjelderup", "Norway", "Comum"),
                ("Antonio Nusa", "Norway", "Comum"),
                ("Aron Dønnum", "Norway", "Comum"),
                ("David Møller Wolfe", "Norway", "Comum"),
                ("Erling Haaland", "Norway", "Comum"),
                ("Erling Haaland", "Norway", "Comum"),
                ("Jorgen Strand Larsen", "Norway", "Comum"),
                ("Kristoffer Vassbakk Ajer", "Norway", "Comum"),
                ("Kristoffer Vassbakk Ajer", "Norway", "Comum"),
                ("Leo Ostigard", "Norway", "Comum"),
                ("Martin Ødegaard", "Norway", "Comum"),
                ("Morten Thorsby", "Norway", "Comum"),
                ("Oscar Bobb", "Norway", "Comum"),
                ("Patrick Berg", "Norway", "Comum"),
                ("Sander Berge", "Norway", "Comum"),
                ("Team Logo", "Norway", "Comum"),
                ("Torbjørn Heggem", "Norway", "Comum"),
                // Panama
                ("Adalberto Carrasquilla", "Panama", "Comum"),
                ("Alberto Quintero", "Panama", "Comum"),
                ("Anibal Godoy", "Panama", "Comum"),
                ("Carlos Harvey", "Panama", "Comum"),
                ("Cesar Blackman", "Panama", "Comum"),
                ("Cristian Martinez", "Panama", "Comum"),
                ("Edgar Barcenas", "Panama", "Comum"),
                ("Eric Davis", "Panama", "Comum"),
                ("Fidel Escobar", "Panama", "Comum"),
                ("Jose Cordoba", "Panama", "Comum"),
                ("Jose Fajardo", "Panama", "Comum"),
                ("Luis Mejia", "Panama", "Comum"),
                ("Michael Amir Murillo", "Panama", "Comum"),
                ("Team Logo", "Panama", "Comum"),
                // Panini
                ("Panini Logo", "Panini", "Comum"),
                // Paraguay
                ("Andres Cubas", "Paraguay", "Comum"),
                ("Angel Romero", "Paraguay", "Comum"),
                ("Diego Gomez", "Paraguay", "Comum"),
                ("Diego Gomez", "Paraguay", "Comum"),
                ("Fabian Balbuena", "Paraguay", "Comum"),
                ("Gustavo Gomez", "Paraguay", "Comum"),
                ("Juan Jose Caceres", "Paraguay", "Comum"),
                ("Julio Enciso", "Paraguay", "Comum"),
                ("Junior Alonso", "Paraguay", "Comum"),
                ("Mathias Villasanti", "Paraguay", "Comum"),
                ("Miguel Almiron", "Paraguay", "Comum"),
                ("Omar Alderete", "Paraguay", "Comum"),
                ("Orlando Gill", "Paraguay", "Comum"),
                ("Ramon Sosa", "Paraguay", "Comum"),
                ("Roberto Fernandez", "Paraguay", "Comum"),
                ("Team Logo", "Paraguay", "Comum"),
                // Portugal
                ("Bernardo Silva", "Portugal", "Comum"),
                ("Bruno Fernandes", "Portugal", "Comum"),
                ("Cristiano Ronaldo", "Portugal", "Comum"),
                ("Cristiano Ronaldo", "Portugal", "Especial"),
                ("Diogo Costa", "Portugal", "Comum"),
                ("Diogo Dalot", "Portugal", "Comum"),
                ("Francisco Trincao", "Portugal", "Comum"),
                ("Goncalo Inacio", "Portugal", "Comum"),
                ("Goncalo Ramos", "Portugal", "Comum"),
                ("Joao Cancelo", "Portugal", "Comum"),
                ("Joao Felix", "Portugal", "Comum"),
                ("Joao Neves", "Portugal", "Comum"),
                ("Jose Sa", "Portugal", "Comum"),
                ("Nuno Mendes", "Portugal", "Comum"),
                ("Pedro Neto", "Portugal", "Comum"),
                ("Rafael Leao", "Portugal", "Comum"),
                ("Ruben Dias", "Portugal", "Comum"),
                ("Ruben Neves", "Portugal", "Comum"),
                ("Team Logo", "Portugal", "Comum"),
                ("Team Photo", "Portugal", "Comum"),
                ("Vitinha", "Portugal", "Comum"),
                // Qatar
                ("Abdulaziz Hatem", "Qatar", "Comum"),
                ("Ahmed Al Ganehi", "Qatar", "Comum"),
                ("Almoez Ali", "Qatar", "Comum"),
                ("Assim Madibo", "Qatar", "Comum"),
                ("Boualem Khoukhi", "Qatar", "Comum"),
                ("Hassan Al-Haydos", "Qatar", "Comum"),
                ("Homam Ahmed", "Qatar", "Comum"),
                ("Karim Boudiaf", "Qatar", "Comum"),
                ("Lucas Mendes", "Qatar", "Comum"),
                ("Mohammed Waad", "Qatar", "Comum"),
                ("Pedro Miguel", "Qatar", "Comum"),
                ("Sultan Albrake", "Qatar", "Comum"),
                ("Tarek Salman", "Qatar", "Comum"),
                // Saudi Arabia
                ("Abdullah Alkhaibari", "Saudi Arabia", "Comum"),
                ("Abdulrahman Al-Aboud", "Saudi Arabia", "Comum"),
                ("Abdulrahman Al-Sanbi", "Saudi Arabia", "Comum"),
                ("Hassan Altambakti", "Saudi Arabia", "Comum"),
                ("Jihad Thakri", "Saudi Arabia", "Comum"),
                ("Marwan Alsahafi", "Saudi Arabia", "Comum"),
                ("Moteb Al-Harbi", "Saudi Arabia", "Comum"),
                ("Musab Aljuwayr", "Saudi Arabia", "Comum"),
                ("Nasser Aldawsari", "Saudi Arabia", "Comum"),
                ("Saleh Abu Alshamat", "Saudi Arabia", "Comum"),
                ("Saleh Alshehri", "Saudi Arabia", "Comum"),
                ("Salem Aldawsari", "Saudi Arabia", "Comum"),
                ("Saud Abdulhamid", "Saudi Arabia", "Comum"),
                ("Team Logo", "Saudi Arabia", "Comum"),
                ("Ziyad Aljohani", "Saudi Arabia", "Comum"),
                // Scotland
                ("Angus Gunn", "Scotland", "Comum"),
                ("Anthony Ralston", "Scotland", "Comum"),
                ("Grant Hanley", "Scotland", "Comum"),
                ("Jack Hendry", "Scotland", "Comum"),
                ("John McGinn", "Scotland", "Comum"),
                ("John Souttar", "Scotland", "Comum"),
                ("Kenny McLean", "Scotland", "Comum"),
                ("Lewis Ferguson", "Scotland", "Comum"),
                ("Lyndon Dykes", "Scotland", "Comum"),
                ("Ryan Christie", "Scotland", "Comum"),
                ("Scott McKenna", "Scotland", "Comum"),
                ("Scott McTominay", "Scotland", "Comum"),
                ("Team Logo", "Scotland", "Comum"),
                // Senegal
                ("Abdoulaye Seck", "Senegal", "Comum"),
                ("Boulaye Dia", "Senegal", "Comum"),
                ("Edouard Mendy", "Senegal", "Comum"),
                ("Habib Diarra", "Senegal", "Comum"),
                ("Idrissa Gana Gueye", "Senegal", "Comum"),
                ("Iliman Ndiaye", "Senegal", "Comum"),
                ("Ismail Jakobs", "Senegal", "Comum"),
                ("Ismaila Sarr", "Senegal", "Comum"),
                ("Kalidou Koulibaly", "Senegal", "Comum"),
                ("Krepin Diatta", "Senegal", "Comum"),
                ("Lamine Camara", "Senegal", "Comum"),
                ("Moussa Niakhate", "Senegal", "Comum"),
                ("Nicolas Jackson", "Senegal", "Comum"),
                ("Pape Gueye", "Senegal", "Comum"),
                ("Pape Matar Sarr", "Senegal", "Comum"),
                ("Sadio Mane", "Senegal", "Especial"),
                // South Africa
                ("Iqraam Rayners", "South Africa", "Comum"),
                ("Khuliso Mudau", "South Africa", "Comum"),
                ("Khuliso Mudau", "South Africa", "Comum"),
                ("Khulumani Ndamane", "South Africa", "Comum"),
                ("Mohau Nkota", "South Africa", "Comum"),
                ("Oswin Appollis", "South Africa", "Comum"),
                ("Ronwen Williams", "South Africa", "Comum"),
                ("Samukele Kabini", "South Africa", "Comum"),
                ("Sipho Chaine", "South Africa", "Comum"),
                ("Sipho Mbule", "South Africa", "Comum"),
                ("Siyabonga Ngezana", "South Africa", "Comum"),
                ("Thalente Mbatha", "South Africa", "Comum"),
                // South Korea
                ("Han-beom Lee", "South Korea", "Comum"),
                ("Hee-chan Hwang", "South Korea", "Comum"),
                ("Heung-min Son", "South Korea", "Comum"),
                ("Hyeon-Gyu Oh", "South Korea", "Comum"),
                ("Hyeon-woo Jo", "South Korea", "Comum"),
                ("Jae-sung Lee", "South Korea", "Comum"),
                ("Jens Castrop", "South Korea", "Comum"),
                ("Kang-in Lee", "South Korea", "Comum"),
                ("Myung-jae Lee", "South Korea", "Comum"),
                ("Seung-Gyu Kim", "South Korea", "Comum"),
                ("Seung-ho Paik", "South Korea", "Comum"),
                ("Son Heung-min", "South Korea", "Especial"),
                ("Team Logo", "South Korea", "Comum"),
                ("Young-woo Seol", "South Korea", "Comum"),
                ("Yu-min Cho", "South Korea", "Comum"),
                // Spain
                ("Alvaro Morata", "Spain", "Comum"),
                ("Aymeric Laporte", "Spain", "Comum"),
                ("Dani Carvajal", "Spain", "Comum"),
                ("Dani Olmo", "Spain", "Comum"),
                ("Dean Huijsen", "Spain", "Comum"),
                ("Fabian Ruiz", "Spain", "Comum"),
                ("Ferran Torres", "Spain", "Comum"),
                ("Lamine Yamal", "Spain", "Comum"),
                ("Lamine Yamal", "Spain", "Comum"),
                ("Lamine Yamal", "Spain", "Especial"),
                ("Lamine Yamal", "Spain", "Especial"),
                ("Marc Cucurella", "Spain", "Comum"),
                ("Martin Zubimendi", "Spain", "Comum"),
                ("Mikel Merino", "Spain", "Comum"),
                ("Mikel Oyarzabal", "Spain", "Comum"),
                ("Nico Williams", "Spain", "Comum"),
                ("Pedri", "Spain", "Comum"),
                ("Pedro Porro", "Spain", "Comum"),
                ("Robin Le Normand", "Spain", "Comum"),
                ("Rodri", "Spain", "Comum"),
                ("Rodri", "Spain", "Comum"),
                ("Rodri", "Spain", "Comum"),
                ("Rodri", "Spain", "Comum"),
                ("Rodri", "Spain", "Comum"),
                ("Rodri", "Spain", "Comum"),
                ("Team Logo", "Spain", "Comum"),
                ("Team Photo", "Spain", "Comum"),
                ("Team Photo", "Spain", "Comum"),
                ("Unai Simon", "Spain", "Comum"),
                // Sweden
                ("Alexander Isak", "Sweden", "Comum"),
                ("Anthony Elanga", "Sweden", "Comum"),
                ("Daniel Svensson", "Sweden", "Comum"),
                ("Gabriel Gudmundsson", "Sweden", "Comum"),
                ("Hugo Larsson", "Sweden", "Comum"),
                ("Isak Hien", "Sweden", "Comum"),
                ("Jesper Karlstrom", "Sweden", "Comum"),
                ("Ken Sema", "Sweden", "Comum"),
                ("Lucas Bergvall", "Sweden", "Comum"),
                ("Roony Bardghji", "Sweden", "Comum"),
                ("Team Logo", "Sweden", "Comum"),
                ("Victor Johansson", "Sweden", "Comum"),
                ("Victor Nilsson Lindelof", "Sweden", "Comum"),
                ("Viktor Gyokeres", "Sweden", "Comum"),
                ("Yasin Ayari", "Sweden", "Comum"),
                // Switzerland
                ("Ardon Jashari", "Switzerland", "Comum"),
                ("Aurele Amenda", "Switzerland", "Comum"),
                ("Dan Ndoye", "Switzerland", "Comum"),
                ("Denis Zakaria", "Switzerland", "Comum"),
                ("Fabian Rieder", "Switzerland", "Comum"),
                ("Granit Xhaka", "Switzerland", "Comum"),
                ("Gregor Kobel", "Switzerland", "Comum"),
                ("Johan Manzambi", "Switzerland", "Comum"),
                ("Manuel Akanji", "Switzerland", "Comum"),
                ("Michel Aebischer", "Switzerland", "Comum"),
                ("Nico Elvedi", "Switzerland", "Comum"),
                ("Remo Freuler", "Switzerland", "Comum"),
                ("Ruben Vargas", "Switzerland", "Comum"),
                ("Silvan Widmer", "Switzerland", "Comum"),
                ("Team Logo", "Switzerland", "Comum"),
                ("Yvon Mvogo", "Switzerland", "Comum"),
                ("Zeki Amdouni", "Switzerland", "Comum"),
                // Tunisia
                ("Aissa Laidouni", "Tunisia", "Comum"),
                ("Ali Abdi", "Tunisia", "Comum"),
                ("Aymen Dahmen", "Tunisia", "Comum"),
                ("Elias Achouri", "Tunisia", "Comum"),
                ("Elias Saad", "Tunisia", "Comum"),
                ("Ellyes Skhiri", "Tunisia", "Comum"),
                ("Ferjani Sassi", "Tunisia", "Comum"),
                ("Hannibal Mejbri", "Tunisia", "Comum"),
                ("Hazem Mastouri", "Tunisia", "Comum"),
                ("Ismael Gharbi", "Tunisia", "Comum"),
                ("Mohamed Ali Ben Romdhane", "Tunisia", "Comum"),
                ("Montassar Talbi", "Tunisia", "Comum"),
                ("Naim Sliti", "Tunisia", "Comum"),
                ("Sayfallah Ltaief", "Tunisia", "Comum"),
                ("Team Logo", "Tunisia", "Comum"),
                ("Yan Valery", "Tunisia", "Comum"),
                ("Yassine Meriah", "Tunisia", "Comum"),
                // Turkey
                ("Abdulkerim Bardakci", "Turkey", "Comum"),
                ("Arda Guler", "Turkey", "Comum"),
                ("Arda Guler", "Turkey", "Comum"),
                ("Baris Alper Yilmaz", "Turkey", "Comum"),
                ("Caglar Soyuncu", "Turkey", "Comum"),
                ("Can Uzun", "Turkey", "Comum"),
                ("Ferdi Kadioglu", "Turkey", "Comum"),
                ("Hakan Calhanoglu", "Turkey", "Comum"),
                ("Irfan Can Kahveci", "Turkey", "Comum"),
                ("Ismail Yuksek", "Turkey", "Comum"),
                ("Kaan Ayhan", "Turkey", "Comum"),
                ("Kenan Yildiz", "Turkey", "Comum"),
                ("Kerem Akturkoglu", "Turkey", "Comum"),
                ("Merih Demiral", "Turkey", "Comum"),
                ("Mert Muldur", "Turkey", "Comum"),
                ("Orkun Kokcu", "Turkey", "Comum"),
                ("Team Logo", "Turkey", "Comum"),
                ("Ugurcan Cakir", "Turkey", "Comum"),
                ("Yunus Akgun", "Turkey", "Comum"),
                ("Zeki Celik", "Turkey", "Comum"),
                // Ukraine
                ("Team Logo", "Ukraine", "Comum"),
                // United States
                ("Alex Freeman", "United States", "Comum"),
                ("Antonee Robinson", "United States", "Comum"),
                ("Brenden Aaronson", "United States", "Comum"),
                ("Chris Richards", "United States", "Comum"),
                ("Christian Pulisic", "United States", "Comum"),
                ("Christian Pulisic", "United States", "Especial"),
                ("Christian Roldan", "United States", "Comum"),
                ("Diego Luna", "United States", "Comum"),
                ("Folarin Balogun", "United States", "Comum"),
                ("Haji Wright", "United States", "Comum"),
                ("Haji Wright", "United States", "Comum"),
                ("Malik Tillman", "United States", "Comum"),
                ("Malik Tillman", "United States", "Comum"),
                ("Mark McKenzie", "United States", "Comum"),
                ("Math Freese", "United States", "Comum"),
                ("Ricardo Pepi", "United States", "Comum"),
                ("Tanner Tessmann", "United States", "Comum"),
                ("Team Logo", "United States", "Comum"),
                ("Timothy Weah", "United States", "Comum"),
                ("Tyler Adams", "United States", "Comum"),
                ("Weston McKenny", "United States", "Comum"),
                // Uruguay
                ("Darwin Nunez", "Uruguay", "Comum"),
                ("Facundo Pellistri", "Uruguay", "Comum"),
                ("Federico Valverde", "Uruguay", "Comum"),
                ("Federico Valverde", "Uruguay", "Especial"),
                ("Federico Valverde", "Uruguay", "Especial"),
                ("Federico Valverde", "Uruguay", "Especial"),
                ("Federico Vinas", "Uruguay", "Comum"),
                ("Guillermo Varela", "Uruguay", "Comum"),
                ("Jose Maria Gimenez", "Uruguay", "Comum"),
                ("Manuel Ugarte", "Uruguay", "Comum"),
                ("Mathias Olivera", "Uruguay", "Comum"),
                ("Maxi Araujo", "Uruguay", "Comum"),
                ("Nahitan Nandez", "Uruguay", "Comum"),
                ("Ronald Araujo", "Uruguay", "Comum"),
                ("Santiago Mele", "Uruguay", "Comum"),
                ("Sebastian Caceres", "Uruguay", "Comum"),
                ("Sergio Rochet", "Uruguay", "Comum"),
                ("Team Logo", "Uruguay", "Comum"),
                // Uzbekistan
                ("Abbosbek Fayzullaev", "Uzbekistan", "Comum"),
                ("Azizbek Turgunboev", "Uzbekistan", "Comum"),
                ("Eldor Shomurodov", "Uzbekistan", "Comum"),
                ("Farrukh Savfiev", "Uzbekistan", "Comum"),
                ("Husniddin Aliqulov", "Uzbekistan", "Comum"),
                ("Igor Sergeev", "Uzbekistan", "Comum"),
                ("Jaloliddin Masharipov", "Uzbekistan", "Comum"),
                ("Jamshid Iskanderov", "Uzbekistan", "Comum"),
                ("Khojiakbar Alijonov", "Uzbekistan", "Comum"),
                ("Khojimat Erkinov", "Uzbekistan", "Comum"),
                ("Oston Urunov", "Uzbekistan", "Comum"),
                ("Otabek Shukurov", "Uzbekistan", "Comum"),
                ("Rustamjon Ashurmatov", "Uzbekistan", "Comum"),
                ("Sherzod Nasrullaev", "Uzbekistan", "Comum"),
                ("Team Logo", "Uzbekistan", "Comum"),
                ("Umar Eshmurodov", "Uzbekistan", "Comum"),
                // World Cup History
                ("Official Ball", "World Cup History", "Comum"),
                ("Official Emblem", "World Cup History", "Comum"),
                ("Official Emblem", "World Cup History", "Comum"),
                ("Official Emblem", "World Cup History", "Comum"),
                ("Official Mascots", "World Cup History", "Comum"),
                ("Official Slogan", "World Cup History", "Comum"),
            };
        }

        // Sorteia um jogador aleatório da lista
        public static (string Nome, string Selecao, string Tipo) SortearJogador()
        {
            var lista = GetTodosJogadores();
            var rng = new Random();
            return lista[rng.Next(lista.Count)];
        }

        // Monta o nome do arquivo de imagem seguindo o padrão:
        // "Selecao - COD NUM - Nome - Jogador"
        // Como não temos o código/número, usamos nome direto para localizar
        public static string BuscarCaminhoImagem(string nomeJogador, string selecao, string tipo)
        {
            var pastaImagens = Path.Combine(AppContext.BaseDirectory, "Imagens");
            if (!Directory.Exists(pastaImagens)) return "";

            string nomeBusca = nomeJogador.ToLower().Trim();
            string selecaoBusca = selecao.ToLower().Trim();
            string tipoBusca = tipo.ToLower().Trim();

            var arquivos = Directory.GetFiles(pastaImagens, "*.png")
                .Where(f =>
                {
                    string nomeArq = Path.GetFileNameWithoutExtension(f).ToLower();
                    return nomeArq.Contains(nomeBusca)
                        && nomeArq.Contains(selecaoBusca)
                        && nomeArq.Contains(tipoBusca);
                })
                .OrderBy(f => f) // pega sempre o primeiro (sem "(2)", "(3)"...)
                .ToList();

            return arquivos.FirstOrDefault() ?? "";
        }
    }
}